# SPDX-FileCopyrightText: 2024 Collegiate Edu-Nation
#
# SPDX-License-Identifier: GPL-3.0-or-later

site_name: chatbot-util docs

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: collegiate-edu-nation/chatbot-util
repo_url: https://github.com/collegiate-edu-nation/chatbot-util

copyright: Copyright 2024-2025 Collegiate Edu-Nation

plugins:
  - mkdocstrings

markdown_extensions:
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Welcome: index.md
  - instructions.md
  - reference.md
  - license.md
