#!/usr/bin/env bash

set -o pipefail
box() { boxes -d ansi -s $(tput cols); } 2> /dev/null
failed() {
  echo -e "\n\033[1;31mBuild failed.\033[0m"
  cleanup
  exit 1
}
interrupted() {
  echo -e "\n\033[1;33mInterrupted.\033[0m"
  cleanup
  popd &> /dev/null
  exit 0
}
cleanup() {
  if ps -p $NODE_SERVER_PID &> /dev/null; then
   kill $NODE_SERVER_PID &> /dev/null
  fi
  if ps -p $PYTHON_SERVER_PID &> /dev/null; then
   kill $PYTHON_SERVER_PID &> /dev/null
  fi
}

trap 'failed' ERR
trap 'interrupted' INT

echo -e "\033[1;33mruff...\033[0m"
ruff check | box

echo -e "\n\033[1;33mpyright...\033[0m"
pyright 2> /dev/null | box

echo -e "\n\033[1;33mcoverage...\033[0m"
pushd . &> /dev/null
cd back
coverage run -m unittest 2> /dev/null | box
popd &> /dev/null

pushd . &> /dev/null
cd front
echo -e "\n\033[1;33meslint...\033[0m"
npx eslint . | box
echo -e "\n\033[1;33mnpm tests...\033[0m"
CI=true npm test &> /dev/null | box
popd &> /dev/null

echo -e "\n\033[1;33mcypress tests...\033[0m"
npm run dev --prefix front &> /dev/null &
NODE_SERVER_PID=$!
pushd . &> /dev/null
cd back
python -m src.chatbot_util &> /dev/null &
PYTHON_SERVER_PID=$!
popd &> /dev/null
pushd . &> /dev/null
cd front
npx cypress run 2> /dev/null | box
popd &> /dev/null
cleanup

echo -e "\n\033[1;33mbuild...\033[0m"
nix build 2> /dev/null | box

echo -e "\n\033[1;32mBuild succeeded.\033[0m"
