#!/usr/bin/env bash

set -o pipefail
box() { boxes -d ansi -s $(tput cols); } 2> /dev/null
failed() {
  echo -e "\n\033[1;31mDocs build failed.\033[0m"
  exit 1
}

trap 'failed' ERR

echo -e "\n\033[1;33mfrontend...\033[0m"
pushd . &> /dev/null
cd front
npx typedoc &> /dev/null | box
popd &> /dev/null

echo -e "\n\033[1;33mbackend...\033[0m"
pushd . &> /dev/null
cd back
mkdocs build 2> /dev/null | box
popd &> /dev/null

echo -e "\n\033[1;32mDocs build succeeded.\033[0m"
