#!/usr/bin/env bash

set -o pipefail
failed() {
  echo -e "\n\033[1;31mLaunch failed.\033[0m"
  exit 1
}
interrupted() {
  echo -e "\n\033[1;33mInterrupted.\033[0m"
  popd &> /dev/null
  exit 0
}

trap 'failed' ERR
trap 'interrupted' INT

echo -e "\033[1;33mfrontend...\033[0m"
npm run build --prefix front

echo -e "\n\033[1;33mbackend...\033[0m"
pushd . &> /dev/null
cd back
python -m src.chatbot_util
